### PR TITLE
Implement response.getHeaders()

### PR DESCRIPTION
**Pull request by sergioregueira**
As commented in #211, I have just implemented the `response.getHeaders()` method (defined in `OutgoingMessage`).

[Node.js specification](https://nodejs.org/docs/latest-v10.x/api/http.html#http_response_getheaders) says the method returns a shallow copy, so I serialize and parse the internal `_headers` object before returning it to avoid additional dependencies.

### CODE REVIEW

**Comment by sergioregueira** [comment]
Furthermore, if you agree, I would like to replace the references in unit tests to `response._getHeaders()` (flagged as deprecated in 2.0) with `response.getHeaders()` (excluding the specific tests of that method).

**Comment by eugef** [comment]
Hi @sergioregueira , thanks for the PR. it looks good to me.
Please go ahead and do the changes in unit tests.

**Comment by sergioregueira** [comment]
Unit tests changed. Take a look at the other pull request before merging this one to fix the non related CI errors.

**Comment by eugef** [comment]
@sergioregueira could you rebase your branch against the latest master - the build should become green

**Comment by sergioregueira** [comment]
Branch rebased and eslint errors fixed.

**Comment by eugef** [comment]
Great, thanks

**Pull request merged**
