### PR TITLE
Add sendStatus() response method to mockResponse.

### PR DESCRIPTION
**Pull request by jaydub2099**
I have been using express.js res.sendStatus(statusCode) locally and noticed that node-mocks-http didn't include this method in mockResponse so this pull request adds the method in.

### CODE REVIEW

**Comment by howardabrams** [comment]
Seems like a reasonable addition. Can you include a tests or two to validate this?

Thanks!

**Comment by jaydub2099** [comment]
Ok I added a test for this following the examples in test-mockResponse.js - This is my first pull request so hopefully I did this correctly.

**Comment by JohnnyEstilles** [comment]
@jaydub2099 adding `.sendStatus()` to `mockResponse` is an awesome idea. However, your implementation is somewhat incomplete.

`.sendStatus()` was introduced in the Express 4.x API. Below is a comparison of the Express 4.x implementation with yours:

Description | Express 4.x | Your PR
--- | :---: | :---:
Sets the status code | :heavy_check_mark: | :heavy_check_mark: 
Sends string representation for well know status codes<br>(e.g. "OK" for 200, "Not Found" for 404, etc.) | :heavy_check_mark: | :x: 
Sends numeric representation for other status codes | :heavy_check_mark: | :heavy_check_mark: 
Sets content-type header to `text/plain` (using the `.type()` method) | :heavy_check_mark: | :x: 

In my opinion your implementation at minimum should:

1. Set status code (yours already does)
2. Send either string or numeric representation of the status code, depending on whether the status is well known (yours send the numeric status code for all; should not be difficult to implement)
3. Set the content-type header to `text/plain` (since `mockResponse` does not yet implement the `.type()` method you can do this manually in the mean time)

> NOTE: Unit testing is essential, so make sure you include tests for any new or updated implementation

I will be submitting a PR implementing `.type()` soon .. :-)

@howardabrams, while this is a great addition to the project, I would suggest holding off on merging it until the implementation mimics that of Express 4.x.

**Comment by JohnnyEstilles** [comment]
I've already implemented the `.type()` method in PR #42. I will update this PR to mimic the Express 4.x implementation of `.sendStatus()`.

**Comment by JohnnyEstilles** [comment]
Closing in favor of #48

**Pull request closed without merging**
