### PR TITLE
Allow for specifying `{ method: undefined }`

### PR DESCRIPTION
**Pull request by michielbdejong**
We want to test how our code responds to a http IncomingMessage where the method is undefined.

### CODE REVIEW

**Comment by eugef** [comment]
Hi @michielbdejong, could you please give an example how the `method` of the `IncomingMessage` might be undefined? How do you even able to send such a request?

**Comment by michielbdejong** [comment]
Ha, you're right, https://nodejs.org/api/http.html#http_class_http_incomingmessage says it's always a `string`, so it should not be necessary, but the following happens:
1. [@types/node says](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L284) that IncomingMessage#method is optional.
2. If we write `const method: string = request.method;` then TypeScript will complain something to the effect of 'cannot assign `<string | undefined>` to `<string>`.
3. So in order to stop that TypeScript compile error, we change our code to `const method: string = request.method || 'GET';`
4. Now the branch coverage of that line is only 50% because jest says our unit tests are not testing the case where request.method is undefined.
5. we want to write a unit test where request.method is undefined, so that we can achieve 100% branch coverage.

So sounds to me like the `?` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L284 is essentially incorrect here? Maybe I misunderstood, I'm pretty new to branch coverage maximisation for TypeScript code.

**Comment by michielbdejong** [comment]
Ah I guess the [comment](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/http.d.ts#L282) above that line explains why the `?` is there.

**Comment by eugef** [comment]
Indeed, that comment explains. 

But this module is meant to be used only for testing `http.Server` requests.
In this context - `method` cannot be `undefined`.

I suggest a workaround for your case:
```
const req  = httpMocks.createRequest();
req.method = undefined;
```

**Pull request closed without merging**
