### PR TITLE
add some feature

### PR DESCRIPTION
**Pull request by cpd0101**

### CODE REVIEW

**Comment by howardabrams** [comment]
Thank you for the feature. Could you add some unit tests that verify these new functions? I would love to have the tests as part of the same PR. Thank you.

**Comment by eugef** [comment]
@cpd0101 are you still interested in writing some tests for this feature?

**Comment by LoneRifle** [comment]
I've just forked @cpd0101 's repo; I'll try to make time to flesh out the unit tests (and perhaps some documentation) and submit a PR to supersede this one in due course.

**Comment by LoneRifle** [comment]
PRs filed - 1 against @cpd0101's branch so that this can have tests, and 1 against master in case the tests do not get merged.

**Comment by eugef** [comment]
LGTM, @howardabrams what do you think?

**Pull request merged**
