### PR TITLE
Add end, send and render events for async testing.

### LINKED ISSUE #6: 'end' or 'close' event or callback for response
The example in the readme assumes that the response is sync. Since I'm testing a wrapper around an actual http API, the response is async, so I need an event or callback. Neither "end" nor "close" seem to get emitted, and I don't think I'm missing something, since the end method doesn't bother.

I can provide a patch, but would like to get confirmation that it would get merged etc.

### PR DESCRIPTION
**Pull request by invernizzie**
This closes #6. We can write tests for asyncrhonous responses as shown below.

Code under test:

``` javascript
function myHandler(request, response) {
  setTimeout(function() {
    response.end();
  }, 1000);
}
```

``` javascript
exports['End is called'] = function (test) {
  request = httpMocks.createRequest();
  var response = httpMocks.createResponse({
    eventEmitter: EventEmitter
  });

  response.on('end', function () {
    test.ok(response._isEndCalled());
    test.done();
  });

  myHandler(request, response);
};
```

### CODE REVIEW

**Comment by knowmad** [comment]
Thanks for this code. It looks like it will solve my, as well as others', problems with async responses. Unfortunately, I'm running into a problem getting this to work. When I use the code as shown in the example, I get the following error -- "ReferenceError: EventEmitter is not defined."

If I then define EventEmitter, I can never seem to get an event handler to call my .on function. I even tried putting the emit call directly into my test and it still didn't work. I am running the test under Mocha if that makes any difference. Thanks for any help.

**Comment by knowmad** [comment]
Figured it out. Here's what is working for me:

var events = require('events');
var ee = events.EventEmitter;
var response = httpMocks.createResponse({
          eventEmitter: ee
        });

**Comment by howardabrams** [comment]
Would creating a mock version of EventEmitter be sufficient? Could you give me a test case you would like to see, and we can try to come up with something?

**Comment by knowmad** [comment]
It looks like you are loading a mock emitter in the mockResponse.js at line 29. The mock emitter was not working for me when I tried to use it by not sending any eventEmitter option when calling createResponse(). My test code is working when I used the version above. 

The main thing we need is to be able to have our tests wait while the request is processed. Due to node's async style, that was not happening when the tests were placed immediately after calling the route handler as shown in your sample. I suspect that's due to our making database calls as part of processing the request.

Thoughts?

**Pull request merged**
