### PR TITLE
This is a better pull to fix issues with express "fresh" check used by SendStream

### PR DESCRIPTION
**Pull request by jaslo**

### CODE REVIEW

**Comment by JohnnyEstilles** [comment]
@jaslo ... Thank you for submitting this PR. Your PR seems two address two separate issues.

1. exposing `_headers` (as node does in the `OutgoingMessage()` class in `/lib/_http_outgoing.js`)
2. using a "real" event emitter

For future reference, please submit individual PRs for separate/unrelated issues.

Regarding the `_headers` issue, this is definite a bug that needs to be fixed. I've already addressed the in `2.0`, but that won't be released for a while, so I will gladly merge this change for you now.

Regarding the "real" event emitter issue, the current version already allows you to use a real event emitter if you so choose by passing it as an option to the `.createResponse()`  method. The option is undocumented, but available. You can, for example:

```js
var EventEmitter = require('events').EventEmitter
var response = httpMocks.createResponse({ eventEmitter: EventEmitter });
```

This issue is also address in `2.0`, but since the current code base provides the ability to BYO event emitter, I'm not too keen on merging this change.

So, I would gladly merge your PR if you could do the following:

1. Remove the code related to the `EventEmitter` issue
2. Squash your changes related to the `_headers` issue into a single commit (the resulting PR requires changing a few lines of code in a single file, so a single commit is more than sufficient)

As soon as you make these changes I will merge and publish a new version on `npm`.

Thanks again. I really appreciate your work on this issue!

**Comment by jaslo** [comment]
Right, I think we chatted about the EventEmitter thing before. I'll reformat the change and resubmit.

**Comment by JohnnyEstilles** [comment]
Awesome! :-)

**Comment by JohnnyEstilles** [comment]
I will update the project's README to document the BYO `EventEmitter` (as well as `WritableStream`) options.

**Pull request closed without merging**
