### PR TITLE
feat: add convenience method _getJSONData

### PR DESCRIPTION
**Pull request by austince**
Thanks for the lib! How would you feel about a small method to parse returned data as JSON? Would cut down on some common duplicate code we have. If you like the idea, I'll add some examples to the README / tests as well.

### CODE REVIEW

**Comment by howardabrams** [comment]
Looks like a good idea, so yeah, let's flesh out the feature. Thanks for the suggestion.

**Comment by austince** [comment]
Added:
- a test case
- ts defs
- example files
- README examples

Let me know if there's anywhere else that needs to be updated.

**Comment by austince** [comment]
Hey @howardabrams, do you have any time to give this a peek? Thanks!

**Comment by austince** [comment]
What is the release process like @howardabrams? Should I bump the version and create a PR?

**Comment by eugef** [comment]
I can publish a new release tomorrow.

**Comment by howardabrams** [comment]
I got 'er done. Thanks for your patience, @austince, see v 1.7.4

Noticed that we really need to update our package dependency tree ... may have to do another release.

**Pull request merged**
